### ISSUE TITLE
The image has spots

### ISSUE THREAD

**Issue by Circle-Kai** [elerac/EasyPySpin#4]
Thank you for providing this package.
The images saved in the SDK are normal, but spots appear when using EasyPySpin.
What parameters can I adjust to improve this problem?

You can see some spots above the image.
![](https://i.imgur.com/d8eWSGg.jpg)

**Comment by elerac** [comment]
Hi, @Circle-Kai !

Your camera has RGB color sensor, right? The spots you are talking about is probably caused by the color filter array.
EasyPySpin returns the bayer pattern image ([like the second one](https://en.wikipedia.org/wiki/Bayer_filter#/media/File:Colorful_spring_garden_Bayer_+_RGB.png)). So, you need to do demosaicing after capturing the image.
Try the code below.
```python
import cv2
import EasyPySpin

cap = EasyPySpin.VideoCapture(0)
ret, frame = cap.read()

frame_bgr = cv2.demosaicing(frame, cv2.COLOR_BayerBG2BGR) # The second argument may need to be changed depending on your sensor.

cv2.imwrite("frame_bgr.png", frame_bgr)
```

**Comment by Circle-Kai** [comment]
Because I want to get grayscale images, I use image. Convert() to convert images . I added this code before GetNDArray().
```python
image_converted = image.Convert(PySpin.PixelFormat_Mono8, PySpin.HQ_LINEAR)
```
https://github.com/elerac/EasyPySpin/blob/76192a93fa1b4b2b1b0ffb451d7e466e3341a397/EasyPySpin/videocapture.py#L135

If there is an error, please tell me again, thanks

**Comment by elerac** [comment]
Did you solve it?
That sounds like a good idea too. I'm glad if you solved it.

**Comment by Circle-Kai** [comment]
Yes, it has been resolved. Thank you.
